#!/usr/bin/env python3
"""Check tracked ownership, source size and protected paths; optionally write the map."""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def git(*args):
    return subprocess.check_output(["git", "-C", str(ROOT), *args])


def tracked_files():
    return sorted(p for p in git("ls-files", "-z").decode().split("\0") if p)


def role(path, roles):
    if path in roles:
        return roles[path]
    name = Path(path).name
    conventional = {
        "LICENSE": "Apache-2.0 license for authored project source.",
        ".gitignore": "Exclude private state, secrets and generated artifacts from Git.",
        ".editorconfig": "Editor whitespace and text conventions.",
        "CONTRIBUTING.md": "Contribution, verification and canonical master-plan links.",
    }
    if name in conventional:
        return conventional[name]
    if path.startswith(".github/workflows/"):
        return "Manual phase-closeout verification for this exact agent commit."
    if name == "codebase-map.md":
        return "Generated exhaustive Git path and ownership index."
    raise ValueError("Missing role: " + path)


def check(write=False):
    files = tracked_files()
    roles = json.loads((ROOT / "scripts/map-roles.json").read_text())
    stale = sorted(set(roles) - set(files))
    if stale:
        raise ValueError("Stale roles: " + ", ".join(stale))
    sizes = []
    for name in files:
        path = ROOT / name
        if not path.is_file() or path.is_symlink():
            raise ValueError("Missing/non-regular tracked file: " + name)
        if re.search(r"(^|/)(\.DS_Store|\.agents|AGENTS\.md|node_modules|\.env(?!\.example$)[^/]*)(/|$)", name) or re.search(r"\.(pem|key|p12)$", name):
            raise ValueError("Protected tracked path: " + name)
        if path.suffix in {".go", ".py", ".sh"}:
            lines = len(path.read_text().splitlines())
            sizes.append((lines, name))
            if lines > 300:
                raise ValueError("Source responsibility review required: " + name + " (" + str(lines) + " lines)")
        role(name, roles)
    rendered = "# Codebase map\n\nGenerated by scripts/source_check.py --write. Each tracked path has one role.\n\n| Path | Role |\n| --- | --- |\n"
    rendered += "".join("| `" + name + "` | " + role(name, roles).replace("|", "\\|") + " |\n" for name in files)
    target = ROOT / "docs/architecture/codebase-map.md"
    if write:
        target.write_text(rendered)
    elif not target.exists() or target.read_text() != rendered:
        raise ValueError("Codebase map is stale; run scripts/source_check.py --write")
    print("Source/map checks passed:", len(files), "tracked files; largest", sorted(sizes, reverse=True)[:3])


if __name__ == "__main__":
    if sys.argv[1:] not in [[], ["--write"]]:
        raise SystemExit("usage: source_check.py [--write]")
    check(sys.argv[1:] == ["--write"])
